spring:
  application:
    name: gateway-service  # The name registered in Eureka


  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE  # Load balanced URI from Eureka
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=api/account/**

server:
  port: 8080


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

